### ISSUE TITLE
Check for encodings in uploaded IF files

### ISSUE THREAD

**Issue by Robert-Christopher** [quintype/quintype-validator#109]
As a publisher/QA, I should be able to understand the files that have encoding other than `UTF-8`, in the validation results

**Acceptance Criteria**

- [x] Check and print encoding type in the file level
- [ ] Print only the files details of non `UTF-8` files
- [ ] Check if author file upload validation errors out proper file name (authors-<PUBLISHER-NAME>-<5 DIGITS>.txt.gz
)

**Comment by RashmiMelagiri** [comment]
Verified the files which has UTF-8 data and its working fine.
