### ISSUE TITLE
Allowing temporary-hero-image-url with localhost domain

### ISSUE THREAD

**Issue by Robert-Christopher** [quintype/quintype-validator#110]
Currently, validator checks for valid **temporary-hero-image-url** other than **http(s)://localhost** domain.

**Acceptance Criteria:**

- [x] Should consider **http(s)://localhost** domain as a valid URL

- [x] Should consider the port number. Ex: http(s)://localhost:3000. Port number will be dynamic

**Comment by radhika-c** [comment]
Tested on production and working as expected.
