### ISSUE TITLE
Fix the SEO interface with stricter types

### ISSUE THREAD

**Issue by Robert-Christopher** [quintype/quintype-validator#111]
As a user, `seo` key of story should not accept any random values.  It should follow the below format.

```
"seo":{
    "meta-description":"Some meta description",
    "meta-title":"Some title",
    "meta-keywords":["keyword1", "keyword2"]
  }
```

All fields are optional, the data types are as follows,

meta-description should be `string`
meta-title should be `string`
meta-keywords should be `Array of strings`

**Comment by RashmiMelagiri** [comment]
Tested the issue in production env. Closing the issue
