### ISSUE TITLE
Direct Text Input not working for a specific story

### ISSUE THREAD

**Issue by ddhar28** [quintype/quintype-validator#120]
**Issue**
Direct Text Input not working for a specific story with a large `body` content.

**Comment by ddhar28** [comment]
**Observations**

- Other text inputs get validated as expected
- Modifying the body tag of the same story with something simpler makes it work
- For the specific body content, in the Network tab, it is observed that the api call fails and under Console tab, a CORS error is seen. CORS error might not be the issue as it is occurring only for a specific body content

**Comment by manu6010** [comment]
Closing ticket.
