### ISSUE TITLE
Results Aggregations

### ISSUE THREAD

**Issue by Robert-Christopher** [quintype/quintype-validator#37]
As a publisher, should be able to read an aggregated results of the validations that was done on the intermediate files

**Acceptance Criteria**

- [x] Should be aggregated results for each error or warning type
- [x] Should display the following details in each aggregations

```
1) Total number of stories
2) Total number of stories which are valid
3) Stories with errors or warning, grouped by error messages with the following data points
a) Message
b) All the external-id's affected
c) Type of level, 'Error' or 'Warning'
```

**Sample**

```
story elements is missing
external-1 external-2
```

**Comment by RashmiMelagiri** [comment]
Scenarios:
1. Verify adding the direct input json in validator , result aggregation should show with Total number of stories and errors with external-ids  and warnings.
2. Verify adding the file upload type in validator, result aggregation should show with Total number of stories and errors with external-ids  and warnings.
3. Verify adding the s3 upload type in validator, result aggregation should show with Total number of stories and errors with external-ids  and warnings.
4. Verify all the types for sections/author/entity tags/stories and expected the results  aggregation should with Total number of stories and errors with external-ids  and warnings.
