### ISSUE TITLE
Update and fix editor types

### ISSUE THREAD

**Issue by Robert-Christopher** [quintype/quintype-validator#39]
The editor types needs to be updated, so that the validator results are really correct, the following types need to be checked and updated accordingly

```
1) Story
2) Section
3) Author
4) Entity
5) Tag
```

Also the public documentation needs to be updated accordingly

**Comment by radhika-c** [comment]
Scenarios:
1. An input given to validator with mandatory fields in a story, section, author, tag and entity should not throw any error.
2. An input given to validator with missing mandatory fields in a story , section, author, tag and entity should throw error.
3. An input given to validator with valid types for the mandatory and non mandatory in a story , section, author, tag and entity should not throw any error.
4. An input given to validator with invalid types for the mandatory and non mandatory fields in a story , section, author, tag and entity should throw error.
