### ISSUE TITLE
Aggregate all details of a validation run in a single downloadable file

### ISSUE THREAD

**Issue by ddhar28** [quintype/quintype-validator#45]
As a user, one should be able to download a single file containing all details of that validation run (stats, errors, warnings and affected external-ids) from the Validator result page.

**Acceptance criteria**

- [x] Downloadable link in Validator result page

- [ ] File name must contain validation run timestamp

- [ ] File must have the following content:
- Stats: Number of total stories, failed and valid stories and other information if any
- List of all errors and warnings if any with corresponding affected external-ids

**Comment by radhika-c** [comment]
1. Given input to validator, results page should have only single downloadable link.
2. Name of the file should be appended with time-stamp.
3. file should have following fields(error-type,path,log-level,external-id).

**Comment by RashmiMelagiri** [comment]
Tested but still production deploy is pending.
