### ISSUE TITLE
Modify UI for Validator result page

### ISSUE THREAD

**Issue by ddhar28** [quintype/quintype-validator#46]
**Requirement**
A new design is required for the Result page of Migrator Validator results, which should cater to the below mentioned requirements.

- should include placement for the following:

- [ ] Statistics - e.g. total number of  stories validated, no of failed and successful stories

- [ ] Link/button to a downloadable file containing validation results

- [ ] Errors and warnings of the validation results

**NOTE:**
This is the design for website validator. https://app.zeplin.io/project/5b02b0eecc20083961194f04/screen/5def5d28eff6c9106d00aab6
The required Result page design can be similar but we require placement of additional elements as mentioned above.

**Comment by ddhar28** [comment]
Followed up with the design team. Waiting on the design to proceed further.

**Comment by asifquintype** [comment]
@StInGDeaDlY  @ddhar28 Updating a draft design. Let me know your thoughts. 

![Validator 2 0 Results page](https://user-images.githubusercontent.com/41146965/82287925-f2872300-99be-11ea-97ff-a231064fc955.png)

**Comment by ddhar28** [comment]
Completed testing by @radhika-c . Deployment pending.
