### ISSUE TITLE
Validate the file name while uploading

### ISSUE THREAD

**Issue by Robert-Christopher** [quintype/quintype-validator#66]
As a developer/QA, validator should validate for file names and make sure the are following the naming conventions

**Acceptance Criteria**

- [x] Should check if the file name starts with one of the following 1) Story- 2) Sections- 3) Authors- 4) Users-
- [x] Should check if the file name ends with a 5 digit non-repeating number

**Comment by SarvaBharan** [comment]
This feature is built only for "File upload" as of now.
