### ISSUE TITLE
Slug of the section should always be in lowercase, with hyphen separated values

### ISSUE THREAD

**Issue by Robert-Christopher** [quintype/quintype-validator#70]
For a developer/QA, validator should throw error if slug of a section does not follow the below constraints.

**Acceptance Criteria**

- [x] Slug should be alphanumeric with hyphen as a delimiter of words. 
- [x] Alphabets should be in lowercase. 
- [x] Consecutively occurring hyphens should not be present. 
- [x] No other special characters should be allowed

**Comment by ddhar28** [comment]
As discussed with @StInGDeaDlY from Platform team, there is already an issue raised to fix the section slug bug in bold editor- https://github.com/quintype/itsman/issues/3557
For now, we will be following the below format for a slug.

- slug should be alphanumeric with hyphen as a delimiter of words. 
- Alphabets should be in lowercase. 
- Multiple consecutively occurring hyphens should be replaced with single hyphen. 
- No other special characters should be allowed

**Comment by RashmiMelagiri** [comment]
Tested on production env and It works fine.
