### ISSUE TITLE
Author validation in Story & Author intermediate format

### ISSUE THREAD

**Issue by Robert-Christopher** [quintype/quintype-validator#71]
As a developer/QA, author in story is validated

**Acceptance Criteria**

- [x] Username attribute should be validated for missing value
- [x] Username value should be as same as name value
- [x] Email attribute should be validated for missing value

**Comment by RashmiMelagiri** [comment]
Tested on production . Works fine and closing the ticket

**Comment by RashmiMelagiri** [comment]
Testing done on local.. its works fine.
