### ISSUE TITLE
Validation support for question story element

### ISSUE THREAD

**Issue by Robert-Christopher** [quintype/quintype-validator#74]
Below are the mandatory fields.

- **type** - 'text'
- **subtype** - 'question'
- **text** - html string of the following format 
```
<p>
  question
</p>
```

Optional fields:

- **metadata** - 
```
{
  "interviewer": {
    "name": name,
    ...
  },
  "key": "value"
}
```

**Comment by RashmiMelagiri** [comment]
Tested on production env, works fine.
