### ISSUE TITLE
Validation support for answer story element

### ISSUE THREAD

**Issue by Robert-Christopher** [quintype/quintype-validator#75]
Below are the mandatory fields.

- **type** - 'text'
- **subtype** - 'answer'
- **text** - html string of the following format 
```
<p>
  answer
</p>
```

Optional fields:

- **metadata** - 
```
{
  "interviewee": {
    "name": name,
    ...
  },
  "key": "value"
}
```

**Comment by RashmiMelagiri** [comment]
Tested  on production env and works fine.
