### ISSUE TITLE
Validation support for blockquote story element

### ISSUE THREAD

**Issue by Robert-Christopher** [quintype/quintype-validator#77]
Below are the mandatory fields.

- **type** - 'text'
- **subtype** - 'blockquote'
- **text** - html string of the following format 
```
<div>
  <blockquote>some quote</blockquote>
  <span class=\"attribution\">John Doe</span>
</div>
```
- **metadata** - 
  - Mandatory key: "content"
```
{
    "content": "some quote"
    "attribution": "John Doe"
}
```

**Comment by RashmiMelagiri** [comment]
Verified the blockquote element in production Validator and it works fine.
