### ISSUE TITLE
Validation support for attachment story element

### ISSUE THREAD

**Issue by Robert-Christopher** [quintype/quintype-validator#78]
Below are the mandatory fields.

- **type** - 'file'
- **subtype** - 'attachment'
- **file-name** - string
- **url** - string
- **s3-key** - string
- **content-type** - string
- **metadata** - 
  - Mandatory key: "file-size"
```
{
    "file-size": 1234
}
```

**Comment by ddhar28** [comment]
User will not know the accurate s3 paths and urls for the attached files beforehand. Putting on hold.
