### ISSUE TITLE
Validation support for also read story element

### ISSUE THREAD

**Issue by Robert-Christopher** [quintype/quintype-validator#80]
Below are the mandatory fields.

- **type** - 'text'
- **subtype** - 'also-read'
- **text** - string
- **metadata** - 
  - Mandatory key: "linked-story-id"
```
{
    "linked-story-id": "valid uuid"
    "linked-story": {
        "headline" : string
        "...": "..."
     }
}
```

**Comment by ddhar28** [comment]
Currently, the user will not know the linked story ids beforehand, so putting the card on hold.
