### ISSUE TITLE
Validation support for references story element

### ISSUE THREAD

**Issue by Robert-Christopher** [quintype/quintype-validator#81]
Below are the mandatory fields.

- **type** - 'composite'
- **subtype** - 'references'
- **story-elements** - Array
  Mandatory keys:
  - **type** - 'text'
  - **text** - string
  - **metadata** 
    - **name** - string
    - **url** - string
```
[
    {
      "subtype": null,
      "metadata": {
        "name": "Paul Pogba",
        "url": "https://onefootball.com/",
        "description": "football info page"
      },
      "text": "<div><p>Paul Pogba</p><p><a href=\"https://onefootball.com/\">football info page</a></p></div>",
      "type": "text"
    }
]
```

**Comment by RashmiMelagiri** [comment]
Tested in production and it works fine.
