### ISSUE TITLE
Validation support for bigfact story element

### ISSUE THREAD

**Issue by Robert-Christopher** [quintype/quintype-validator#82]
Below are the mandatory fields.

- **type** - 'text'
- **subtype** - 'bigfact'
- **metadata** - 
```
{
  "content": "Title of bigfact",
  "attribution": "Description of Bigfact"
}
```
- **text** - html string of the following format 
```
<div>
  <div class=\"bigfact-title\">Big fact</div>
  <div class=\"bigfact-description\">bigfact description</div>
</div>
```

**Comment by RashmiMelagiri** [comment]
Completed the devbox, Currently validation was done for any html tag. But for bigfact element, 2 div tags should be there as part of text value. This check is missing . Hence moving back to Dev

**Comment by RashmiMelagiri** [comment]
Scenarios:
1. Validate the bigfact element in story json via Direct Input. 
2. Validate the bigfact element in story json via File upload.
3. Check and Validate  for Mandatory fields of bigfact element in story json.
4. Check and validate for fields values of bigfact element in story json.

**Comment by RashmiMelagiri** [comment]
Tested in production env and works fine
